version: '3.8'

services:

  jenkins:

    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root

    # Web UI
    # Agent Interface
    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  jenkins-agent:

    image: jenkins/inbound-agent
    container_name: jenkins-agent
    restart: unless-stopped

    depends_on:
      - jenkins

    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=vm-agent
      - JENKINS_SECRET=your-agent-secret

# Persistant Data Volume for Jenkins
volumes:
  jenkins_home:
    driver: local
    name: jenkins_home
